# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
