# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
