# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_user_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
